name: moviedb
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tmdb_api: ^2.2.0 # Specify the version or use a version range
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.25.4
  firebase_auth:
  cloud_firestore:
  rounded_loading_button_plus: ^3.0.1
  achievement_view: ^1.0.1
  shared_preferences: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Updated version

flutter:
  uses-material-design: true
