// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8OKSWQbZ7klAJTmCbe0RWZpjz5KHOj6I',
    appId: '1:777346711149:web:f2f3f8e72cb6323918c964',
    messagingSenderId: '777346711149',
    projectId: 'loginfirebase-1f2a9',
    authDomain: 'loginfirebase-1f2a9.firebaseapp.com',
    storageBucket: 'loginfirebase-1f2a9.appspot.com',
    measurementId: 'G-N70KZKKB77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEszlSBK4LZgzy_R5LgN7lMr1-F4A_WEs',
    appId: '1:777346711149:android:5b1088ec03d369fc18c964',
    messagingSenderId: '777346711149',
    projectId: 'loginfirebase-1f2a9',
    storageBucket: 'loginfirebase-1f2a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfMkTXr45ZCHXKhr0QCa33vdqLeYLtHQ',
    appId: '1:777346711149:ios:4f00077f2657fc9018c964',
    messagingSenderId: '777346711149',
    projectId: 'loginfirebase-1f2a9',
    storageBucket: 'loginfirebase-1f2a9.appspot.com',
    iosBundleId: 'com.example.moviedb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfMkTXr45ZCHXKhr0QCa33vdqLeYLtHQ',
    appId: '1:777346711149:ios:4eb5b5e6b9b9ba2a18c964',
    messagingSenderId: '777346711149',
    projectId: 'loginfirebase-1f2a9',
    storageBucket: 'loginfirebase-1f2a9.appspot.com',
    iosBundleId: 'com.example.moviedb.RunnerTests',
  );
}
